---
name: bookly
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  get_it: ^7.6.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12

  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  go_router: ^10.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
